os:
  - linux
  - osx

language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
addons:
  apt:
    packages:
      - openssl
      - libssl-dev
      - faketime
      - libscope-guard-perl
      - libtest-tcp-perl
  homebrew:
    packages:
      - libfaketime
      - openssl

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CMAKE_OPTS=" -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://cpanmin.us | sudo perl - App::cpanminus; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpanm --notest Scope::Guard; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpanm --notest Test::TCP; fi

install:
  - go get -t -v ./... || true
  - cd $GOPATH/src/github.com/mpiraux/pigotls && make

script:
  - go test
