os:
  - linux
  - osx

language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
addons:
  apt:
    packages:
      - openssl
      - libssl-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/openssl@1.1/include/openssl /usr/local/include/openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.dylib /usr/local/lib/libcrypto.dylib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.a /usr/local/lib/libcrypto.a; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/openssl@1.1/lib/libssl.dylib /usr/local/lib/libssl.dylib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/openssl@1.1/lib/libssl.a /usr/local/lib/libssl.a; fi

install:
  - go get -t -v ./... || true
  - cd $GOPATH/src/github.com/mpiraux/pigotls && make

script:
  - go test
